[versions]
logback = "1.5.6"
scrimage = "4.1.3"
twelvemonkeys = "3.11.0"

[libraries]
batik = "org.apache.xmlgraphics:batik-transcoder:1.17"
gson = "com.google.code.gson:gson:2.11.0"
hamcrest = "org.hamcrest:hamcrest-core:3.0"
imageio-batik = { module = "com.twelvemonkeys.imageio:imageio-batik", version.ref = "twelvemonkeys" }
imageio-psd = { module = "com.twelvemonkeys.imageio:imageio-psd", version.ref = "twelvemonkeys" }
jave = "ws.schild:jave-core:3.5.0"
junit = "org.junit.jupiter:junit-jupiter:5.10.3"
junit-platform = "org.junit.platform:junit-platform-launcher:1.10.3"
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
mockwebserver = "com.squareup.okhttp3:mockwebserver3-junit5:5.0.0-alpha.14"
okio = "com.squareup.okio:okio:3.9.0"
scrimage-core = { module = "com.sksamuel.scrimage:scrimage-core", version.ref = "scrimage" }
scrimage-formats-extra = { module = "com.sksamuel.scrimage:scrimage-formats-extra", version.ref = "scrimage" }
scrimage-webp = { module = "com.sksamuel.scrimage:scrimage-webp", version.ref = "scrimage" }
slf4j-api = "org.slf4j:slf4j-api:2.0.16"
telegram-bot-api = "com.github.pengrad:java-telegram-bot-api:7.8.0"
tika = "org.apache.tika:tika-core:2.9.2"

[plugins]
runtime = "org.beryx.runtime:1.13.1"
shadow = "com.github.johnrengelman.shadow:8.1.1"
